name: CI
on: [workflow_dispatch, push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: coursier/cache-action@v7
    - uses: coursier/setup-action@v3
      with:
        java-version: adopt@1.11
    - name: Compile & Test
      run: bash ci.sh